"""Match NCRB police-district names to GADM (c. 2010) map districts.

NCRB reports by police district: commissionerates, rural/urban splits, railway police,
and districts created after the map boundaries were drawn. ALIAS folds those into the
map district that covers them; DROP lists units with no geography (railways, CID, ...).
"""
import difflib
import re

# ------------------------------------------------------------- district level
NCRB_STATE_TO_GADM = {
    "A & N ISLANDS": "Andaman and Nicobar", "A&N ISLANDS": "Andaman and Nicobar",
    "ANDAMAN & NICOBAR ISLANDS": "Andaman and Nicobar",
    "D & N HAVELI": "Dadra and Nagar Haveli", "D&N HAVELI": "Dadra and Nagar Haveli",
    "DADRA & NAGAR HAVELI": "Dadra and Nagar Haveli",
    "DAMAN & DIU": "Daman and Diu", "JAMMU & KASHMIR": "Jammu and Kashmir",
    "ODISHA": "Orissa", "UTTARAKHAND": "Uttaranchal",
    "TELANGANA": "Andhra Pradesh",  # GADM boundaries pre-date the 2014 split
    "DELHI UT": "Delhi", "LADAKH": "Jammu and Kashmir", "PUDUCHERRY": "Puducherry",
}

# Police districts that are not a geographic district (railways, CID, etc.)
DROP = re.compile(r"\b(TOTAL|RLY|RAILWAY|RAILWAYS|GRP|CID|CRIME BRANCH|STF|CB CID|IGI AIRPORT|"
                  r"C I D|CBCID|SRP|BORDER|G R P|G R P|R P O|RPO|ATS|ANTI TERRORIST|ECONOMIC OFFENCES|CRIME|I AND P|IRRIGATION|COASTAL|SPL CELL|SPECIAL CELL|EOW|BIEO|TRAFFIC|CAW|ESTATE|ATS|SECURITY|"
                  r"ALL DISTRICTS|NRI|CYBER CELL|OTHER UNITS|SPL NARCOTIC|DISCOM)\b")
STRIP = re.compile(r"\b(COMMR|COMMISSIONARATE|COMMISSIONRATE|COMMISSIONERATE|COMMISIONERATE|COMMISSIONER|RURAL|URBAN|"
                   r"CITY|DIST|DISTRICT|OUTER|DEHAT|GRAMEEN|PD|POLICE|SP|PC|HQ|HQRS|R|U|NORTH|SOUTH|EAST|WEST|CENTRAL)\b")

# NCRB spelling -> GADM spelling (after normalisation)
ALIAS = {
    "MUMBAI": "GREATER BOMBAY", "NAVI MUMBAI": "THANE", "BEED": "BID", "BULDHANA": "BULDANA",
    "GADCHIROLI": "GARHCHIROLI", "GONDIA": "GONDIYA", "NASIK": "NASHIK", "RAIGAD": "RAIGARH",
    "KOLKATA": "KOLKATA", "HOWRAH": "HAORA", "HOOGHLY": "HUGLI", "BARDHAMAN": "BARDDHAMAN",
    "BURDWAN": "BARDDHAMAN", "ASANSOL DURGAPUR": "BARDDHAMAN", "ASANSOL": "BARDDHAMAN",
    "DURGAPUR": "BARDDHAMAN", "BIDHANNAGAR": "NORTH 24 PARGANAS", "BARRACKPORE": "NORTH 24 PARGANAS",
    "24 PARGANAS NORTH": "NORTH 24 PARGANAS", "24 PARGANAS SOUTH": "SOUTH 24 PARGANAS",
    "DIAMOND HARBOUR": "SOUTH 24 PARGANAS", "BARUIPUR": "SOUTH 24 PARGANAS",
    "BANGALORE": "BANGALORE", "BENGALURU": "BANGALORE", "MYSURU": "MYSORE",
    "HUBLI DHARWAD": "DHARWAD", "BELGAUM": "BELGAUM", "BELAGAVI": "BELGAUM",
    "MANGALORE": "DAKSHIN KANNAD", "DAKSHINA KANNADA": "DAKSHIN KANNAD", "UDUPI": "UDUPI",
    "KALABURAGI": "GULBARGA", "VIJAYAPURA": "BIJAPUR", "BALLARI": "BELLARY", "KGF": "KOLAR",
    "HYDERABAD": "HYDERABAD", "CYBERABAD": "RANGAREDDI", "RANGA REDDY": "RANGAREDDI",
    "RACHAKONDA": "RANGAREDDI", "VIJAYAWADA": "KRISHNA", "VISAKHAPATNAM": "VISHAKHAPATNAM",
    "VIZAG": "VISHAKHAPATNAM", "GUNTUR": "GUNTUR", "TIRUPATHI": "CHITTOOR", "TIRUPATI": "CHITTOOR",
    "RAJAHMUNDRY": "EAST GODAVARI", "WARANGAL": "WARANGAL", "NELLORE": "NELLORE",
    "CHENNAI": "CHENNAI", "CHENGAI": "KANCHEEPURAM", "KANCHIPURAM": "KANCHEEPURAM",
    "TUTICORIN": "THOOTHUKUDI", "TIRUNELVELI": "TIRUNELVELI KATTABO", "NILGIRIS": "NILGIRIS",
    "COIMBATORE": "COIMBATORE", "VILLUPURAM": "VILUPPURAM", "TIRUVALLUR": "THIRUVALLUR",
    "TRICHY": "TIRUCHCHIRAPPALLI", "TIRUCHIRAPPALLI": "TIRUCHCHIRAPPALLI",
    "THIRUVARUR": "TIRUVARUR", "KANYAKUMARI": "KANNIYAKUMARI",
    "TRIVANDRUM": "THIRUVANANTHAPURAM", "THIRUVANANTHAPURAM": "THIRUVANANTHAPURAM",
    "KOCHI": "ERNAKULAM", "ERNAKULAM": "ERNAKULAM", "CALICUT": "KOZHIKODE", "KOZHIKODE": "KOZHIKODE",
    "TRICHUR": "THRISSUR", "THRISSUR": "THRISSUR", "CANNANORE": "KANNUR", "PALGHAT": "PALAKKAD",
    "ALLEPPEY": "ALAPPUZHA", "QUILON": "KOLLAM", "KOLLAM": "KOLLAM",
    "AHMEDABAD": "AHMADABAD", "VADODARA": "VADODARA", "BARODA": "VADODARA", "SURAT": "SURAT",
    "RAJKOT": "RAJKOT", "BANASKANTHA": "BANAS KANTHA", "SABARKANTHA": "SABAR KANTHA",
    "PANCHMAHAL": "PANCH MAHALS", "DANGS": "THE DANGS", "WESTERN RLY": "",
    "GURGAON": "GURGAON", "GURUGRAM": "GURGAON", "FARIDABAD": "FARIDABAD", "MEWAT": "MEWAT",
    "JAIPUR": "JAIPUR", "JODHPUR": "JODHPUR", "SRIGANGANAGAR": "GANGANAGAR", "GANGANAGAR": "GANGANAGAR",
    "DHOLPUR": "DHAULPUR", "JHUNJHUNU": "JHUNJHUNUN", "CHITTORGARH": "CHITTAURGARH",
    "LUCKNOW": "LUCKNOW", "KANPUR NAGAR": "KANPUR NAGAR", "KANPUR DEHAT": "KANPUR DEHAT",
    "ALLAHABAD": "ALLAHABAD", "PRAYAGRAJ": "ALLAHABAD", "FAIZABAD": "FAIZABAD", "AYODHYA": "FAIZABAD",
    "GAUTAMBUDH NAGAR": "GAUTAM BUDDHA NAGAR", "G B NAGAR": "GAUTAM BUDDHA NAGAR",
    "NOIDA": "GAUTAM BUDDHA NAGAR", "BULANDSHAHAR": "BULANDSHAHR", "BARABANKI": "BARA BANKI",
    "SIDDHARTHNAGAR": "SIDDHARTH NAGAR", "MAHARAJGANJ": "MAHRAJGANJ", "KUSHINAGAR": "KUSHINAGAR",
    "SANTKABIR NAGAR": "SANT KABIR NAGAR", "SANT RAVIDAS NAGAR": "SANT RAVI DAS NAGAR",
    "BHADOHI": "SANT RAVI DAS NAGAR", "JYOTIBA PHULE NAGAR": "JYOTIBA PHULE NAGAR",
    "SHRAVASTI": "SHRAWASTI", "LAKHIMPUR KHERI": "KHERI", "KHERI": "KHERI",
    "BHOPAL": "BHOPAL", "INDORE": "INDORE", "JABALPUR": "JABALPUR", "GWALIOR": "GWALIOR",
    "NARSINGHPUR": "NARSIMHAPUR", "KHANDWA": "EAST NIMAR", "KHARGONE": "WEST NIMAR",
    "RAIPUR": "RAIPUR", "DANTEWADA": "DANTEWADA", "KAWARDHA": "KABEERDHAM", "KABIRDHAM": "KABEERDHAM",
    "JANJGIR": "JANJGIR CHAMPA", "JANJGIR CHAMPA": "JANJGIR CHAMPA",
    "PATNA": "PATNA", "PURNEA": "PURNIA", "MONGHYR": "MUNGER", "BAGAHA": "PASHCHIM CHAMPARAN",
    "BETTIAH": "PASHCHIM CHAMPARAN", "MOTIHARI": "PURBA CHAMPARAN", "WEST CHAMPARAN": "PASHCHIM CHAMPARAN",
    "EAST CHAMPARAN": "PURBA CHAMPARAN", "NAUGACHIA": "BHAGALPUR", "KAIMUR": "BHABUA",
    "RANCHI": "RANCHI", "SINGHBHUM EAST": "PURBI SINGHBHUM", "EAST SINGHBHUM": "PURBI SINGHBHUM",
    "JAMSHEDPUR": "PURBI SINGHBHUM", "SINGHBHUM WEST": "PASHCHIMI SINGHBHUM",
    "WEST SINGHBHUM": "PASHCHIMI SINGHBHUM", "CHAIBASA": "PASHCHIMI SINGHBHUM",
    "BHUBANESWAR": "KHORDHA", "CUTTACK": "CUTTACK", "KHURDA": "KHORDHA", "BALASORE": "BALESHWAR",
    "BOLANGIR": "BALANGIR", "SONEPUR": "SONAPUR", "KEONJHAR": "KENDUJHAR", "JAGATSINGHPUR": "JAGATSINGHAPUR",
    "BERHAMPUR": "GANJAM", "ROURKELA": "SUNDARGARH", "NABARANGPUR": "NABARANGAPUR",
    "AMRITSAR": "AMRITSAR", "LUDHIANA": "LUDHIANA", "JALANDHAR": "JALANDHAR", "BATALA": "GURDASPUR",
    "KHANNA": "LUDHIANA", "JAGRAON": "LUDHIANA", "MAJITHA": "AMRITSAR", "TARN TARAN": "AMRITSAR",
    "ROPAR": "RUPNAGAR", "NAWANSHAHR": "NAWAN SHEHAR", "MOHALI": "SAHIBZADA AJIT SINGH NAGAR",
    "SAS NAGAR": "SAHIBZADA AJIT SINGH NAGAR", "FATEHGARH SAHIB": "FATEHGARH SAHIB",
    "SRINAGAR": "SRINAGAR", "JAMMU": "JAMMU", "ANANTNAG": "ANANTNAG", "BARAMULLA": "BARAMULA",
    "KUPWARA": "KUPWARA", "LEH": "LEH LADAKH", "LEH LADAKH": "LEH LADAKH", "POONCH": "PUNCH",
    "DEHRADUN": "DEHRADUN", "HARIDWAR": "HARDWAR", "UDHAM SINGH NAGAR": "UDHAM SINGH NAGAR",
    "GUWAHATI": "KAMRUP", "KAMRUP METRO": "KAMRUP", "SIBSAGAR": "SIBSAGAR",
    "NORTH CACHAR HILLS": "NORTH CACHAR HILLS", "N C HILLS": "NORTH CACHAR HILLS",
    "KARBI ANGLONG": "KARBI ANGLONG", "IMPHAL": "IMPHAL WEST", "IMPHAL EAST": "IMPHAL EAST",
    "IMPHAL WEST": "IMPHAL WEST", "SHILLONG": "EAST KHASI HILLS",
    "AIZAWL": "AIZAWL", "AGARTALA": "WEST TRIPURA", "GANGTOK": "EAST",
    "PANAJI": "NORTH GOA", "MARGAO": "SOUTH GOA",
}

# Districts carved out after the (c. 2010) GADM boundaries, and other spellings -> map district.
# Keys are normalised NCRB names; values are normalised GADM names.
ALIAS.update({
    # Andhra Pradesh / Telangana
    "VISAKHA": "VISHAKHAPATNAM", "MAHABOOB NAGAR": "MAHBUBNAGAR",
    # Arunachal Pradesh
    "DIBANG VALLEY": "UPPER DIBANG VALLEY", "ANJAW": "LOHIT", "K KUMEY": "KURUNG KUMEY",
    "LONGDING": "TIRAP", "RURAL": "PAPUM PARE",
    # Assam
    "BASKA": "NALBARI", "BAKSA": "NALBARI", "CHIRANG": "BONGAIGAON", "UDALGURI": "DARRANG",
    "HAMREN": "KARBI ANGLONG",
    # Bihar
    "ARWAL": "JEHANABAD",
    # Chhattisgarh
    "BALRAMPUR": "SURGUJA", "SURAJPUR": "SURGUJA", "BIZAPUR": "DANTEWADA", "BIJAPUR": "DANTEWADA",
    "SUKMA": "DANTEWADA", "NARAYANPUR": "BASTAR", "JAGDALPUR": "BASTAR", "KONDAGAON": "BASTAR",
    "KABIRDHAM": "KAWARDHA", "GARIYABAND": "RAIPUR", "BALODA BAZAR": "RAIPUR", "BALODBAZAR": "RAIPUR",
    "BALOD": "DURG", "BEMETARA": "DURG", "BEMETRA": "DURG", "MUNGELI": "BILASPUR", "MUNGALI": "BILASPUR",
    # Gujarat
    "AHWA DANG": "THE DANGS", "DANG": "THE DANGS", "HIMATNAGAR": "SABAR KANTHA", "ARVALLI": "SABAR KANTHA",
    "PALANPUR": "BANAS KANTHA", "KUTCH": "KACHCHH", "KUTCH EAST G": "KACHCHH", "KUTCH WEST BHUJ": "KACHCHH",
    "MEHSANA": "MAHESANA", "TAPI": "SURAT", "BOTAD": "BHAVNAGAR", "CHHOTAUDEPUR": "VADODARA",
    "DEVBHUMI DWARKA": "JAMNAGAR", "GIR SOMNATH": "JUNAGADH", "MAHISAGAR": "PANCH MAHALS", "MORBI": "RAJKOT",
    # Haryana
    "MEWAT": "GURGAON", "PALWAL": "FARIDABAD",
    # Himachal Pradesh
    "LAHAUL SPITI": "LAHUL AND SPITI", "BADDIPOLICEDIST": "SOLAN", "BADDI": "SOLAN",
    # Jammu & Kashmir (GADM names carry a region suffix)
    "ANANTNAG": "ANANTNAG KASHMIR SOUTH", "KULGAM": "ANANTNAG KASHMIR SOUTH",
    "AWANTIPORA": "PULWAMA", "SHOPIAN": "PULWAMA", "BARAMULLA": "BARAMULA KASHMIR NORTH",
    "BANDIPORA": "BARAMULA KASHMIR NORTH", "SOPORE": "BARAMULA KASHMIR NORTH", "BUDGAM": "BAGDAM",
    "GANDERBAL": "SRINAGAR", "BADGAM": "BAGDAM", "KARGIL": "KARGIL", "KUPWARA": "KUPWARA MUZAFFARABAD", "HANDWARA": "KUPWARA MUZAFFARABAD",
    "LEH": "LADAKH LEH", "RAMBAN": "DODA", "KISHTWAR": "DODA", "REASI": "UDHAMPUR", "SAMBA": "JAMMU",
    # Jharkhand
    "SARAIKELA": "SARAIKELA KHARSAWAN", "KHUNTI": "RANCHI", "RAMGARH": "HAZARIBAG",
    # Karnataka
    "BANGALORE COMMR": "BANGALORE URBAN", "BENGALURU CITY": "BANGALORE URBAN",
    "BANGALORE CITY": "BANGALORE URBAN", "K G F": "KOLAR", "RAMANAGAR": "BANGALORE RURAL",
    "RAMANAGARA": "BANGALORE RURAL", "CBPURA": "KOLAR", "CHIKKABALLAPUR": "KOLAR", "YADGIRI": "GULBARGA",
    "YADGIR": "GULBARGA",
    # Madhya Pradesh
    "KHARGON": "WEST NIMAR", "ALIRAJPUR": "JHABUA", "SINGRAULI": "SIDHI",
    # Nagaland
    "KIPHIRE": "TUENSANG", "LONGLENG": "TUENSANG", "PEREN": "KOHIMA",
    # Odisha
    "NOWRANGPUR": "NABARANGPUR", "DCP BBSR": "KHORDHA", "DCP CTC": "CUTTACK",
    # Punjab
    "BARNALA": "SANGRUR", "SAS NGR": "RUPNAGAR", "SAS NAGAR": "RUPNAGAR", "MOHALI": "RUPNAGAR",
    "SBS NAGAR": "NAWAN SHEHAR", "FAZILKA": "FIROZPUR", "PATHANKOT": "GURDASPUR", "TARN TARAN": "AMRITSAR",
    # Rajasthan
    "PRATAPGARH": "CHITTAURGARH", "PRAAPGARH": "CHITTAURGARH",
    # Tamil Nadu
    "THIRUNELVELI": "TIRUNELVELI KATTABO", "KRISHNAGIRI": "DHARMAPURI", "TIRUPPUR": "COIMBATORE",
    "CHENNAISUBURBAN": "KANCHEEPURAM", "CHENNAI SUBURBAN": "KANCHEEPURAM",
    # Uttar Pradesh
    "CHITRAKOOT DHAM": "CHITRAKOOT", "FATEHGARH": "FARRUKHABAD", "J P NAGAR": "JYOTIBA PHULE NAGAR",
    "AMROHA": "JYOTIBA PHULE NAGAR", "KANPUR NAGAR": "KANPUR", "KHIRI": "LAKHIMPUR KHERI",
    "KHERI": "LAKHIMPUR KHERI", "LAKHIMPUR KHERI": "LAKHIMPUR KHERI", "KANSHIRAM NAGAR": "ETAH",
    "CSM NAGAR": "SULTANPUR", "RAMABAI NAGAR": "KANPUR DEHAT", "BHIM NAGAR": "MORADABAD",
    "SAMBHAL": "MORADABAD", "PANCHSHIL NAGAR": "GHAZIABAD", "HAPUR": "GHAZIABAD", "SHAMLI": "MUZAFFARNAGAR",
    "PRABUDH NAGAR": "MUZAFFARNAGAR",
    # West Bengal
    "COOCHBEHAR": "KOCHBIHAR", "COOCH BEHAR": "KOCHBIHAR", "MIDNAPUR": "WEST MIDNAPORE",
    "PASCHIM MIDNAPUR": "WEST MIDNAPORE", "PASCHIM MEDINIPUR": "WEST MIDNAPORE",
    "PURAB MIDNAPUR": "EAST MIDNAPORE", "PURAB MEDINIPUR": "EAST MIDNAPORE", "PURBA MEDINIPUR": "EAST MIDNAPORE",
    "BKP CP": "NORTH 24 PARGANAS", "BARRACKPUR": "NORTH 24 PARGANAS", "BIDHANNAGAR": "NORTH 24 PARGANAS",
    "SILIGURI": "DARJILING", "SILIGURI PC": "DARJILING", "DARJEELING": "DARJILING", "BDN CP": "BARDDHAMAN",
    "HOWRAH": "HAORA", "HOWRAH G R P": "", "PURULIA": "PURULIYA", "MALDA": "MALDAH",
    "HOOGHLY": "HUGLI", "CHANDANNAGAR": "HUGLI",
    # Union territories
    "ANDAMAN": "ANDAMAN ISLANDS", "NICOBAR": "NICOBAR ISLANDS", "CAR": "NICOBAR ISLANDS",
    "NORTH AND MIDDLE ANDAMAN": "ANDAMAN ISLANDS", "SOUTH ANDAMAN": "ANDAMAN ISLANDS",
    "A AND N ISLANDS": "ANDAMAN ISLANDS", "DIU": "JUNAGADH", "PONDICHERRY": "PUDUCHERRY",
})

# Census 2011 district spellings (population join)
ALIAS.update({
    "BANDIPORE": "BARAMULA KASHMIR NORTH", "SHUPIYAN": "PULWAMA", "SHAHID BHAGAT SINGH NAGAR": "NAWAN SHEHAR",
    "SAHIBZADA AJIT SINGH NAGAR": "RUPNAGAR", "GARHWAL": "PAURI GARHWAL", "MAHAMAYA NAGAR": "HATHRAS",
    "SANT RAVIDAS NAGAR BHADOHI": "SANT RAVI DAS NAGAR", "KAIMUR BHABUA": "BHABUA",
    "NORTH DISTRICT": "NORTH SIKKIM", "WEST DISTRICT": "WEST SIKKIM", "SOUTH DISTRICT": "SOUTH SIKKIM",
    "EAST DISTRICT": "EAST", "DIMA HASAO": "NORTH CACHAR HILLS", "KAMRUP METROPOLITAN": "KAMRUP",
    "NORTH TWENTY FOUR PARGANAS": "NORTH 24 PARGANAS", "SOUTH TWENTY FOUR PARGANAS": "SOUTH 24 PARGANAS",
    "DEBAGARH": "DEOGARH", "BAUDH": "BOUDH", "SUBARNAPUR": "SONEPUR", "KABEERDHAM": "KAWARDHA",
    "UTTAR BASTAR KANKER": "KANKER", "DAKSHIN BASTAR DANTEWADA": "DANTEWADA",
    "KHARGONE WEST NIMAR": "WEST NIMAR", "NARSIMHAPUR": "NARSINGHPUR", "NARSINGHPUR": "NARSINGHPUR",
    "KHANDWA EAST NIMAR": "EAST NIMAR", "DOHAD": "DAHOD", "MUMBAI SUBURBAN": "GREATER BOMBAY",
    "SRI POTTI SRIRAMULU NELLORE": "NELLORE", "Y S R": "CUDDAPAH", "BANGALORE": "BANGALORE URBAN",
    "CHIKKABALLAPURA": "KOLAR", "THE NILGIRIS": "NILGIRIS", "NICOBARS": "NICOBAR ISLANDS",
})

# Districts created 2015-2024 (NCRB district tables) -> c. 2010 parent map district
ALIAS.update({
    # Andhra Pradesh (2022 reorganisation)
    "NTR": "KRISHNA", "ELURU": "WEST GODAVARI", "NANDYAL": "KURNOOL", "BAPATLA": "GUNTUR", "PALNADU": "GUNTUR",
    "DR BR AMBEDKAR KONASEEMA": "EAST GODAVARI", "KONASEEMA": "EAST GODAVARI", "KAKINADA": "EAST GODAVARI",
    "YSR": "CUDDAPAH", "YSR KADAPA": "CUDDAPAH", "KADAPA": "CUDDAPAH", "ANNAMAYYA": "CUDDAPAH",
    "SRI SATHYA SAI": "ANANTAPUR", "ANAKAPALLI": "VISHAKHAPATNAM", "ALLURI SITHARAMA RAJU": "VISHAKHAPATNAM",
    "PARVATHIPURAM MANYAM": "VIZIANAGARAM", "SPSR NELLORE": "NELLORE", "PRAKASAM": "PRAKASAM",
    # Telangana (2016 reorganisation)
    "RAMAGUNDAM": "KARIMNAGAR", "JAGITYAL": "KARIMNAGAR", "JAGTIAL": "KARIMNAGAR", "PEDDAPALLI": "KARIMNAGAR",
    "RAJANNA SIRICILLA": "KARIMNAGAR", "SURYAPET": "NALGONDA", "YADADRI BHUVANAGIRI": "NALGONDA",
    "BHADRADRI KOTHAGUDEM": "KHAMMAM", "SIDDIPET": "MEDAK", "SANGAREDDY": "MEDAK", "KAMAREDDY": "NIZAMABAD",
    "MAHABUBABAD": "WARANGAL", "JANGAON": "WARANGAL", "JAYASHANKAR BHUPALPALLY": "WARANGAL", "MULUGU": "WARANGAL",
    "HANUMAKONDA": "WARANGAL", "NAGARKURNOOL": "MAHBUBNAGAR", "WANAPARTHY": "MAHBUBNAGAR",
    "JOGULAMBA GADWAL": "MAHBUBNAGAR", "NARAYANPET": "MAHBUBNAGAR", "VIKARABAD": "RANGAREDDI",
    "MEDCHAL MALKAJGIRI": "RANGAREDDI", "NIRMAL": "ADILABAD", "MANCHERIAL": "ADILABAD",
    "KUMURAM BHEEM ASIFABAD": "ADILABAD", "KOMARAM BHEEM ASIFABAD": "ADILABAD",
    # West Bengal police districts
    "PURBA BARDHAMAN": "BARDDHAMAN", "PASCHIM BARDHAMAN": "BARDDHAMAN", "SUNDARBAN": "SOUTH 24 PARGANAS",
    "BARASAT": "NORTH 24 PARGANAS", "BASIRHAT": "NORTH 24 PARGANAS", "BANGAON": "NORTH 24 PARGANAS",
    "RANAGHAT": "NADIA", "KRISHNAGAR": "NADIA", "JANGIPUR": "MURSHIDABAD", "ALIPURDUAR": "JALPAIGURI",
    "RAIGANJ": "UTTAR DINAJPUR", "ISLAMPUR": "UTTAR DINAJPUR", "JHARGRAM": "WEST MIDNAPORE",
    "KALIMPONG": "DARJILING", "BISHNUPUR": "BANKURA",
    # Madhya Pradesh
    "NARMADAPURAM": "HOSHANGABAD", "NIWARI": "TIKAMGARH", "AGAR MALWA": "SHAJAPUR", "MAUGANJ": "REWA",
    "MAIHAR": "SATNA", "PANDHURNA": "CHHINDWARA",
    # Maharashtra
    "MIRA BHAYANDAR VASAI VIRAR": "THANE", "AHILYANAGAR": "AHMEDNAGAR", "CHHATRAPATI SAMBHAJINAGAR": "AURANGABAD",
    "PIMPRI CHINCHWAD": "PUNE", "DHARASHIV": "OSMANABAD", "PALGHAR": "THANE",
    # Rajasthan (2023 districts)
    "DEEG": "BHARATPUR", "BEAWAR": "AJMER", "KEKRI": "AJMER", "KOTPUTLI BEHROR": "JAIPUR", "DUDU": "JAIPUR",
    "DIDWANA KUCHAMAN": "NAGAUR", "ANUPGARH": "GANGANAGAR", "GANGAPUR": "SAWAI MADHOPUR",
    "SHAHPURA": "BHILWARA", "NEEM KA THANA": "SIKAR", "BHIWADI": "ALWAR", "KHAIRTHAL TIJARA": "ALWAR",
    "BALOTRA": "BARMER", "PHALODI": "JODHPUR", "SALUMBAR": "UDAIPUR", "SANCHORE": "JALOR",
    # Karnataka
    "BENGALURU": "BANGALORE RURAL", "VIJAYANAGARA": "BELLARY",
    # Assam
    "HOJAI": "NAGAON", "BISWANATH": "SONITPUR", "CHARAIDEO": "SIBSAGAR", "MAJULI": "JORHAT",
    "SOUTH SALMARA MANKACHAR": "DHUBURI", "WEST KARBI ANGLONG": "KARBI ANGLONG", "BAJALI": "BARPETA",
    "TAMULPUR": "NALNARI",
    # Others
    "NUH": "GURGAON", "CHARKHI DADRI": "BHIWANI", "KASGANJ": "ETAH", "AMETHI": "SULTANPUR",
    "KAIMUR BHABHUA": "BHABUA", "MALERKOTLA": "SANGRUR",
})
ALIAS["TAMULPUR"] = "NALBARI"
ALIAS.update({
    "KALABURGI": "GULBARGA", "SOUTH SALMARA": "DHUBURI", "MANGALURU": "DAKSHIN KANNAD",
    "HUBBALLI DHARWAD": "DHARWAD", "HANSI": "HISAR", "JAYASHANKAR BHUPALPALLI": "WARANGAL",
    "KUMARAM BHEEM ASIFABAD": "ADILABAD", "MULUG": "WARANGAL", "BURDWAN OLD": "BARDDHAMAN",
    "GOMATI": "SOUTH TRIPURA", "SIPAHIJALA": "WEST TRIPURA", "KHOWAI": "WEST TRIPURA", "KOWAI": "WEST TRIPURA",
    "UNAKOTI": "NORTH TRIPURA", "DHALAI": "DHALAI",
    "TENKASI": "TIRUNELVELI KATTABO", "KALLAKURICHI": "VILUPPURAM", "AVADI": "THIRUVALLUR",
    "TAMBARAM": "KANCHEEPURAM", "CHENGALPATTU": "KANCHEEPURAM", "RANIPET": "VELLORE", "TIRUPATTUR": "VELLORE",
    "MAYILADUTHURAI": "NAGAPATTINAM", "SAKTI": "JANJGIR CHAMPA",
    "KHAIRTAL TIJARA": "ALWAR", "TIRUPPATTUR": "VELLORE", "MANENDRAGARH CHIRMIRI BHARATPUR": "KORIYA",
    "SARANGARH BILAIGARH": "RAIGARH", "GAURELA PENDRA MARWARI": "BILASPUR", "SADIA": "TINSUKIA",
    "D AND N HAVELI": "DADRA AND NAGAR HAVELI", "VASANASI": "VARANASI",
    "KHAIRAGARH CHHUIKHADAN GANDAI": "RAJ NANDGAON", "MOHLA MANPUR AMBAGARH CHOUKI": "RAJ NANDGAON",
    "GARO HILLS NORTH": "EAST GARO HILLS", "GARO HILLS SOUTH WEST": "WEST GARO HILLS",
    "KHASI HILLS SOUTH WEST": "WEST KHASI HILLS", "KHASI HILLS EASTERN WEST": "WEST KHASI HILLS",
    "NURPUR": "KANGRA", "NAMSAI": "LOHIT", "NAMCHI": "SOUTH SIKKIM", "PAKYONG": "EAST", "DABWALI": "SIRSA",
    "KAKCHING": "THOUBAL", "VASANASI DEHAT": "VARANASI", "GARO HILLS SOUTH W": "WEST GARO HILLS",
})


def norm(s):
    s = str(s).upper().replace("&", " AND ")
    s = re.sub(r"[^A-Z0-9 ]", " ", s)
    return re.sub(r"\s+", " ", s).strip()



def match(st_raw, dist, by_state, gadm_state_norm):
    n = norm(dist)
    if DROP.search(n):
        return "DROP"
    gs = NCRB_STATE_MAP.get(st_raw) or gadm_state_norm.get(st_raw)
    if gs is None:
        # fuzzy state
        m = difflib.get_close_matches(st_raw, list(gadm_state_norm), n=1, cutoff=0.8)
        if not m:
            return None
        gs = gadm_state_norm[m[0]]
    cands = by_state[gs]
    if len(cands) == 1:  # Delhi, Chandigarh, DNH, Lakshadweep
        return next(iter(cands.values()))
    stripped = re.sub(r"\s+", " ", STRIP.sub("", n)).strip()
    for attempt in (n, ALIAS.get(n), stripped, ALIAS.get(stripped)):
        if not attempt:
            continue
        if attempt in cands:
            return cands[attempt]
        # same words in another order ("KAMENG EAST" = "EAST KAMENG")
        toks = set(attempt.split())
        same = [c for c in cands if set(c.split()) == toks]
        if len(same) == 1:
            return cands[same[0]]
        m = difflib.get_close_matches(attempt, list(cands), n=1, cutoff=0.82)
        if m:
            return cands[m[0]]
    # all query words inside exactly one map name ("NORTH" -> "NORTH SIKKIM")
    toks = set(n.split())
    sup = [c for c in cands if toks <= set(c.split())]
    if len(sup) == 1:
        return cands[sup[0]]
    # Telangana/Andhra Pradesh in 2014: try the other state
    return None




NCRB_STATE_MAP = {norm(k): v for k, v in NCRB_STATE_TO_GADM.items()}
